# Site settings
title: Church Bridge
description: Jesus // Love // Hope
email: Zinchenko.yan@gmail.com


# Site default images and content
logo:
bg-img: 2bg.jpg
avatar: Poter.jpg
blurb: <p><strong>Derell Poter</strong> Consectetur adipisicing        Voluptate eum nesciunt in maiores nisi eius totam sequi harum           reprehenderit expedita <a href="">@mailDerell</a> a doloremque dignissimos accusantium architecto eos velit, aut, id. Odit animi, voluptatibus  esse perferendis <a href="">Facebook</a> labore architecto nemo tenetur perspiciatis libero, provider.
      </p>








# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested